site_name: CommonGAS

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/SgXJJsja67
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@creationartstudios8279

copyright: |
  &copy; 2023 <a href="https://github.com/KhxiSaki"  target="_blank" rel="noopener">CreationArtStudios</a> 

nav:
    - 'Home':
       - 'Overview' :  'index.md'
       - 'Installation' :  'installation.md'
       - 'Setup' :  'setup.md'
       - 'Tutorials' :  'tutorials.md'
       - 'Changelog' : 'changelog.md'

    - 'ModularGameplayActors': 
       - 'Common Modular Character': 'commonmodularcharacter.md'
       - 'Common Modular Pawn': 'commonmodularpawn.md'
       - 'Common Modular Player Controller': 'commonmodularplayercontroller.md'
       - 'Common Modular AI Controller': 'commonmodularaicontroller.md'
       - 'Common Modular Actor': 'commonmodularactor.md'
       - 'Common Modular PlayerState': 'commonmodularplayerstate.md'

    - 'Gameplay Abilities':
        - 'How-to Gameplay Ability': 'howtogameplayability.md'
        - 'CommonGameplayAbility': 'commongameplayability.md'
        - 'Common Ability Set' : 'commonabilityset.md'
        - 'Common Ability Tag Relationship Mapping' : 'commonabilitytagrelationshipmapping.md'
        - 'Common Gameplay Tags' : 'commongameplaytag.md'
        - 'CommonAbilitySystemComponent': 'commonabilitysystemcomponent.md'
        - 'CommonExtensionComponent': 'commonextensioncomponent.md'
        - 'CommonAbilityQueueComponent': 'commonabilityqueuecomponent.md'
        - 'CommonAbilitySystemLibrary' : 'commonabilitysystemlibrary.md'
        - 'CommonGameplayTagLibrary' : 'commongameplaytaglibrary.md'

    - 'Gameplay Effects':
      - 'How to use AttributeSet': 'attributes.md'
      - 'Common Attribute Set': 'commonattributeset.md'
      - 'CommonModMagnitudeCalculation': 'commonmodmagnitudecalculation.md'
      - 'CommonGameplayEffectLibrary' : 'commongameplayeffectlibrary.md'

    - 'Artificial Intelligence':
      - 'State Tree': 'StateTree.md'
      - 'AIModule': 'aimodule.md'

    - 'Gameplay Tasks':
      - 'How-to AbilityTask': 'howtoabilitytask.md'
      - 'PlayMontageAndWaitForEvent': 'playmontageandwaitforevent.md'

    - 'Animation':
      - 'CommonAnimInstance': 'commonaniminstance.md'

    - 'GameFeatures':
      - 'GameFeatureAction_AddAbilities': 'gamefeatureaction_addabilities.md'
      - 'GameFeatureAction_AddInputContextMapping': 'gamefeatureaction_addinputcontextmapping.md'

    - 'Messaging':
       - 'GameplayMessageRouter' : 'gameplaymessagerouter.md'
       - 'GameplayMessageProcessor' : 'gameplaymessageprocessor.md'
       - 'AsyncAction_ListenForGameplayMessage' : 'asyncaction_listenforgameplaymessage.md'
       - 'GameplayMessageSubsystem' : 'gameplaymessagesubsystem.md'
       - 'GameplayMessageTypes2' : 'gameplaymessagetypes2.md'

    - 'Input':
       - 'CommonAbilityInputBindingComponent' : 'commonabilityinputbindingcomponent.md'
       - 'CommonEnhancedInputComponent' : 'commonenhancedinputcomponent.md'
       - 'CommonInputConfig' : 'commoninputconfig.md'
       - 'CommonPlayerControlsComponent' : 'commonplayercontrolscomponent.md'

# Plugins
plugins:
  - search
  - mkdocs-video